import 'package:cloud_firestore/cloud_firestore.dart';

// ============================================================
// InstitutionModel
// Firestore collection: /institutions/{institutionId}
// Created automatically when first report is filed
// Updated nightly by Python AI backend
// ============================================================

// ── Trend enum — matches DB ENUM exactly ─────────────────
enum InstitutionTrend {
  increasing,
  decreasing,
  stable,
  insufficientData,
}

// ── TrendData — for 6-month chart ────────────────────────
class TrendDataPoint {
  final String month;  // e.g. "Jan", "Feb"
  final int count;     // number of reports that month

  const TrendDataPoint({
    required this.month,
    required this.count,
  });

  factory TrendDataPoint.fromMap(Map<String, dynamic> data) {
    return TrendDataPoint(
      month: data['month'] ?? '',
      count: data['count'] ?? 0,
    );
  }

  Map<String, dynamic> toMap() => {
    'month': month,
    'count': count,
  };
}

// ── Main InstitutionModel ─────────────────────────────────
class InstitutionModel {
  final String institutionId;
  final String name;                    // Office name typed by citizen
  final String categoryId;             // FK → categories
  final String district;               // One of 77 Nepal districts
  final String? province;              // One of 7 provinces
  final double? lat;                   // Geolocation
  final double? lng;
  final int totalReports;              // Incremented on each new report
  final int totalUpvotes;              // Sum of upvotes across all reports
  final int transparencyScore;         // 0-100, updated nightly
  final double? avgBribeAmount;        // In NPR, null if no amounts given
  final String? mostCommonComplaint;   // Generated by Pandas mode()
  final String? lastInsight;           // AI-generated summary
  final InstitutionTrend trend;        // vs previous 30 days
  final List<TrendDataPoint> trendData; // Last 6 months chart data
  final DateTime updatedAt;            // Last nightly Python update
  final DateTime createdAt;            // When first report was filed

  const InstitutionModel({
    required this.institutionId,
    required this.name,
    required this.categoryId,
    required this.district,
    this.province,
    this.lat,
    this.lng,
    required this.totalReports,
    required this.totalUpvotes,
    required this.transparencyScore,
    this.avgBribeAmount,
    this.mostCommonComplaint,
    this.lastInsight,
    required this.trend,
    required this.trendData,
    required this.updatedAt,
    required this.createdAt,
  });

  // ── Convert TO Firestore map ─────────────────────────────
  Map<String, dynamic> toMap() {
    return {
      'name':                 name,
      'categoryId':           categoryId,
      'district':             district,
      'province':             province,
      'lat':                  lat,
      'lng':                  lng,
      'totalReports':         totalReports,
      'totalUpvotes':         totalUpvotes,
      'transparencyScore':    transparencyScore,
      'avgBribeAmount':       avgBribeAmount,
      'mostCommonComplaint':  mostCommonComplaint,
      'lastInsight':          lastInsight,
      'trend':                trend.name,
      'trendData':            trendData.map((t) => t.toMap()).toList(),
      'updatedAt':            Timestamp.fromDate(updatedAt),
      'createdAt':            Timestamp.fromDate(createdAt),
    };
  }

  // ── Create FROM Firestore document ───────────────────────
  factory InstitutionModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return InstitutionModel(
      institutionId:        doc.id,
      name:                 data['name']                ?? '',
      categoryId:           data['categoryId']          ?? 'other',
      district:             data['district']            ?? '',
      province:             data['province'],
      lat:                  data['lat'] != null
                              ? (data['lat'] as num).toDouble()
                              : null,
      lng:                  data['lng'] != null
                              ? (data['lng'] as num).toDouble()
                              : null,
      totalReports:         data['totalReports']        ?? 0,
      totalUpvotes:         data['totalUpvotes']        ?? 0,
      transparencyScore:    data['transparencyScore']   ?? 100,
      avgBribeAmount:       data['avgBribeAmount'] != null
                              ? (data['avgBribeAmount'] as num).toDouble()
                              : null,
      mostCommonComplaint:  data['mostCommonComplaint'],
      lastInsight:          data['lastInsight'],
      trend:                _parseTrend(data['trend']),
      trendData:            data['trendData'] != null
                              ? (data['trendData'] as List)
                                  .map((t) => TrendDataPoint.fromMap(
                                      Map<String, dynamic>.from(t)))
                                  .toList()
                              : [],
      updatedAt:            (data['updatedAt'] as Timestamp).toDate(),
      createdAt:            (data['createdAt'] as Timestamp).toDate(),
    );
  }

  // ── Parse trend string to enum ───────────────────────────
  static InstitutionTrend _parseTrend(String? value) {
    switch (value) {
      case 'increasing':        return InstitutionTrend.increasing;
      case 'decreasing':        return InstitutionTrend.decreasing;
      case 'stable':            return InstitutionTrend.stable;
      default:                  return InstitutionTrend.insufficientData;
    }
  }

  // ── Score color label for UI ─────────────────────────────
  // Returns 'high' / 'medium' / 'low' for color coding
  String get scoreLabel {
    if (transparencyScore >= 70) return 'high';
    if (transparencyScore >= 40) return 'medium';
    return 'low';
  }

  // ── Trend display text ───────────────────────────────────
  String get trendText {
    switch (trend) {
      case InstitutionTrend.increasing:        return '⬆️ Worsening';
      case InstitutionTrend.decreasing:        return '⬇️ Improving';
      case InstitutionTrend.stable:            return '➡️ Stable';
      case InstitutionTrend.insufficientData: return '📊 Insufficient data';
    }
  }

  // ── copyWith ─────────────────────────────────────────────
  InstitutionModel copyWith({
    String?              name,
    int?                 totalReports,
    int?                 totalUpvotes,
    int?                 transparencyScore,
    double?              avgBribeAmount,
    String?              mostCommonComplaint,
    String?              lastInsight,
    InstitutionTrend?    trend,
    List<TrendDataPoint>? trendData,
    DateTime?            updatedAt,
  }) {
    return InstitutionModel(
      institutionId:       institutionId,
      name:                name               ?? this.name,
      categoryId:          categoryId,
      district:            district,
      province:            province,
      lat:                 lat,
      lng:                 lng,
      totalReports:        totalReports       ?? this.totalReports,
      totalUpvotes:        totalUpvotes       ?? this.totalUpvotes,
      transparencyScore:   transparencyScore  ?? this.transparencyScore,
      avgBribeAmount:      avgBribeAmount     ?? this.avgBribeAmount,
      mostCommonComplaint: mostCommonComplaint ?? this.mostCommonComplaint,
      lastInsight:         lastInsight        ?? this.lastInsight,
      trend:               trend              ?? this.trend,
      trendData:           trendData          ?? this.trendData,
      updatedAt:           updatedAt          ?? this.updatedAt,
      createdAt:           createdAt,
    );
  }

  @override
  String toString() {
    return 'InstitutionModel('
        'id: $institutionId, '
        'name: $name, '
        'district: $district, '
        'score: $transparencyScore, '
        'reports: $totalReports'
        ')';
  }
}
