// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkAJfnIPw6fucOcpz802QGf0RfVjPFZ_w',
    appId: '1:255919354543:web:c94901c97b46d00c5c9a5a',
    messagingSenderId: '255919354543',
    projectId: 'khulasaa-bbff0',
    authDomain: 'khulasaa-bbff0.firebaseapp.com',
    storageBucket: 'khulasaa-bbff0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcmchZTU4zdH3EANQLHQ42LzSuMSZveNg',
    appId: '1:255919354543:android:3ae7632db049a78e5c9a5a',
    messagingSenderId: '255919354543',
    projectId: 'khulasaa-bbff0',
    storageBucket: 'khulasaa-bbff0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK-9xzcav9V6NWqWovD2EE_75GJV0ExTk',
    appId: '1:255919354543:ios:54645adb2d506bc25c9a5a',
    messagingSenderId: '255919354543',
    projectId: 'khulasaa-bbff0',
    storageBucket: 'khulasaa-bbff0.firebasestorage.app',
    iosBundleId: 'com.example.khulasaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK-9xzcav9V6NWqWovD2EE_75GJV0ExTk',
    appId: '1:255919354543:ios:54645adb2d506bc25c9a5a',
    messagingSenderId: '255919354543',
    projectId: 'khulasaa-bbff0',
    storageBucket: 'khulasaa-bbff0.firebasestorage.app',
    iosBundleId: 'com.example.khulasaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkAJfnIPw6fucOcpz802QGf0RfVjPFZ_w',
    appId: '1:255919354543:web:75c0d50191b49b7d5c9a5a',
    messagingSenderId: '255919354543',
    projectId: 'khulasaa-bbff0',
    authDomain: 'khulasaa-bbff0.firebaseapp.com',
    storageBucket: 'khulasaa-bbff0.firebasestorage.app',
  );
}
